### PR TITLE
Added test line to Read me.txt

### PR DESCRIPTION
**Pull request by pemiller**
@LanceDH You asked someone to do a pull request on this repo just so you could see what it was like. Here you go.

I forked your repo, which makes basically makes a copy of your repo to my account so that I have push permissions. I made the change there and then came back here and submitted this pull request across forks.

Now you can review my changes, make comments, request that I change something about my code, and eventually merge the pull request. Hope this helped.

### CODE REVIEW

**Comment by LanceDH** [comment]
So here's the issue I'm trying to figure out.
You made a pull request with some changes but before I merged I changed something in the readme myself.
Now I got a "This branch has conflicts that must be resolved" because the file in the master is different from the one you edited.
Say there's 2 people that made a pull request to change the readme, I merge your version, don't I get this same conflict with the other person's request because the now merged file has your data in it, while the other person made a pull request on the old version of the file?

**Comment by pemiller** [comment]
This is the scenario you have in your project now. I submitted the pull request but something else changed before you merged my pull request. Now there would be a merge conflict. There are a couple things that could happen next.

Since I do not have permissions to actually push to your repository and you do not have permissions to push to my fork of your repository, there is only one option. The contributors that submit the pull requests are responsible for resolving any merge conflicts on their own branch. In this case, I would be required to make any changes needed to make that green merge button show up. This isn't unreasonable, its just part of life when working on a community project.

There are some cases where you are waiting on someone to do something for you that you really need and they submitted the pull request but then it has merge conflict. If they go AWOL for a while but you really need that code you could copy and paste it into a branch of your own and then close the pull request. You could also fork their fork and then fix the issue and submit a pull request to your original project. This is kind of a rare situation.

As a note, if you are actually working with someone in such a way that you need them to do stuff its probably best to grant them permissions to push to your repository. If they work in your repository then you could also make any changes needed to the pull request yourself. Or the two of you could make commits to the same branch while you work.

**Comment by LanceDH** [comment]
So it's just the nature of the beast to have issues like this when everyone works on a single file?
Would it instead be better to ask for people to work in seperate files for example; 
Say you want to start working on Tanaris, I have you make your own file called Tanaris, and have you work in that.
Meanwhile someone else is working on the Badlands in his own file, both of you finish and both of you request a pull.
Since you both worked on your own files, there is no issue as it will just add both your files to the project.
Or is there a way to have everyone work on a single file that's just not getting through to my head?

**Comment by pemiller** [comment]
Merge conflicts don't always happen when working in a single file. Our merge conflict happened because we both made changes to the end of the file. I actually modified line 1 just as you did and since there wasn't anything after line 1 the merge resolver couldn't find a clean way to place both of our changes.

Say the file was like this:
Line 1
Line A
Line Q

I submit a pull request that looks like: 
Line 1
Line 2
Line A
Line Q

Someone commits this before the merge:
Line 1
Line A
Line B
Line Q

There wouldn't be a merge conflict because its clear that "Line 2" goes between "Line 1" and "Line A", while your change wasn't between that. Merge conflicts are typical at the end of the file or the end of a section of code.

That said if you can structure your addon so that there are files per zone then that might be best. Its typically easier to work on something when its somewhat modular. There is always a trade-off but I wouldn't suggest 1 huge file to hold all the text.

**Comment by LanceDH** [comment]
Aha I think I get it now.
I'll be keeping this community repo and the one from the addon separate just for personal reasons.
For the community side I'll probably go with a 'file per zone' system to also have a better overview for those that want to help.
I'll then move the stuff from those files into the file of the addon when things are done. They'll need manually work to have it fit in anyway.
I'll start working on some basic structure and guide so people can offer their help if they want.

Thanks for the explanation.

**Pull request merged**
